name: SSH to Azure VM

on:
  push:
    branches:
      - development
jobs:
  ssh:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -i "$SSH_KEY" \
          azureuser@50.112.216.238 \
          'echo "Hello, Azure V!"
          ls -la
