name: SSH to Azure VM

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Azure VM and restart app
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@50.112.216.238 << EOF
            set -e
            if [ -f /etc/profile ]; then source /etc/profile; fi
            if [ -f ~/.bash_profile ]; then source ~/.bash_profile; fi
            if [ -f ~/.bashrc ]; then source ~/.bashrc; fi
      
            echo "PM2 location:"
            sudo which pm2
            echo "PATH is:"
            echo \$PATH
      
            cd /home/ubuntu/HomePhase2
            git pull
            pm2 restart 1
          EOF
